### PR TITLE
Add support for the mac-roman encoding

### PR DESCRIPTION
**Pull request by fjl**
This came about because someone asked me to transform a CSV file that uses this encoding last week. It would be nice to have because mac-roman is still used by old software.

mac-roman is supported natively in most CL implementations: 

- SBCL: `:mac-roman` (also `:mac`, `:macintosh`) [src/code/external-formats/enc-mac.lisp](https://github.com/sbcl/sbcl/blob/d35ad6f9bee212499cb827fec3195bf2064c10a2/src/code/external-formats/enc-mac.lisp#L3)
- CMU CL: `:mac-roman`: [src/pcl/simple-streams/external-formats/mac-roman.lisp](https://gitlab.common-lisp.net/cmucl/cmucl/-/blob/master/src/pcl/simple-streams/external-formats/mac-roman.lisp)
- ClozureCL: `:macintosh` (also `:mac-roman`, `:macos-roman`)  [level-1/l1-unicode.lisp](https://github.com/Clozure/ccl/blob/6c1a9458f7a5437b73ec227e989aa5b825f32fd3/level-1/l1-unicode.lisp#L1086)
- LispWorks: `:macos-roman` [external format docs](http://www.lispworks.com/documentation/lw71/LW/html/lw-201.htm#pgfId-892436)
- Clisp: `:mac-roman` [src/nls_mac_roman.c](https://gitlab.com/gnu-clisp/clisp/-/blob/master/src/nls_mac_roman.c)

It is not supported natively in:

- Allegro CL
- ECL
- ABCL

### CODE REVIEW

**Comment by stassats** [comment]
The Copyright line seems to be inaccurate.

**Comment by fjl** [comment]
Not sure what to put there, I just copied it from ascii.lisp

**Comment by fjl** [comment]
Just let me know if additional copyright text needs to be added. For example, I could add my name and the current year there.

**Comment by stassats** [comment]
I see only two options, either it's removed or an additional one is added. The latter seems to be preferable .

**Comment by fjl** [comment]
Updated!

**Pull request merged**
